branches:
  only:
  - packge-builder

image: Visual Studio 2017
configuration: Release
platform: Any CPU

dotnet_csproj:
  patch: false
  file: '**\*.csproj'
  version: '{version}'

nuget:
  disable_publish_on_pr: true

clone_folder: C:\projects\ceras

before_build:
- cmd: nuget restore

build_script:
  - dotnet build "C:\projects\ceras\src\Ceras\Ceras.csproj" --verbosity m --configuration Release
  - dotnet build "C:\projects\ceras\src\Ceras.ImmutableCollections\Ceras.ImmutableCollections.csproj" --verbosity m --configuration Release
  - dotnet build "C:\projects\ceras\tests\Ceras.Test\Ceras.Test.csproj" --verbosity m --configuration Release
#  - dotnet build "C:\projects\ceras\src\Ceras.AotGenerator\Ceras.AotGenerator.csproj" --verbosity m --configuration Release

  - 7z a C:\projects\ceras\ceras_netstandard2.0.zip "C:\projects\ceras\src\Ceras\bin\Any CPU\Release\netstandard2.0\*"
  - 7z a C:\projects\ceras\ceras_net45.zip "C:\projects\ceras\src\Ceras\bin\Any CPU\Release\net45\*"
  - 7z a C:\projects\ceras\ceras_net47.zip "C:\projects\ceras\src\Ceras\bin\Any CPU\Release\net47\*"
#  - 7z a C:\projects\ceras\ceras_UnityAotGenerator.zip "C:\projects\ceras\src\Ceras.AotGenerator\bin\Any CPU\Release\net47\*"

  - ps: .\build.ps1

artifacts:

- path: '**\src\Ceras\bin\**\Ceras*.nupkg'
  name: NuGet Package Ceras

- path: '**\src\Ceras.ImmutableCollections\**\Ceras*.nupkg'
  name: NuGet Package Ceras.ImmutableCollections

- path: ceras_netstandard2.0.zip
  name: Release Folder Zip (.NET Standard 2.0)

- path: ceras_net45.zip
  name: Release Folder Zip (.NET Framework 4.5)

- path: ceras_net47.zip
  name: Release Folder Zip (.NET Framework 4.7)

#- path: ceras_UnityAotGenerator.zip
#  name: AotGenerator for Unity IL2CPP



